# Generated by Django 3.1.1 on 2020-09-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesmodel',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='messagesmodel',
            name='message',
            field=models.TextField(max_length=250),
        ),
    ]
